#pragma once

#include <string>
#include <array>


namespace Tmpl8
{
	class Blueprints
	{
	public:
		Blueprints() {};
		bool LoadBlueprint(int level_id);
		unsigned int ReadBlueprint();
		int GetAutotileId(int center_x, int center_y);

	private:
		bool GetIsWallAdjacent(char adjacent_value);

		bool is_iterator_set{ false };
		std::string::iterator blueprint_it;
		std::string m_loaded_blueprint;

		std::array<std::string, 3> blueprints
		{
			"XXXXXXXXXXXXXXXXXXXX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOPOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOXXXOOXXXOOOX"
			"XOOOOOOOXXOOOOXXOOOX"
			"XOOOOOOOXOOOOOOXOOOX"
			"XOOOOOOOOOOXXOOOOOOX"
			"XOOOOOOOOOXXXXOOOOOX"
			"XXXXXXXXXXXXXXXXXXXX",
			
			"XXXXXXXXXX"
			"XOOOOOOOOX"
			"XOOOOOOOOX"
			"XXXXXXXOOX"
			"XXOXXXXOOX"
			"XOPOOOOOOX"
			"XOOOOOOOOX"
			"XXXXXXXOOX"
			"XXXXXXXOOX"
			"XXXXXXXXXX",

			"XXXXXXXXXXXXXXXXXXXX"
			"XOOOOOOOOOOOOOOOOOOO"
			"XOOOOOOOOOOOOOOOOOOO"
			"XOXXXXXXOXXOXXXOXXXX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOXXOXOXXXXXXXXXXOOX"
			"XOOOOOOXOOOOOOOOOOOX"
			"XOOOOOOXOOOOOOOOOOOX"
			"XOOOOOXXOOOOOXOXXOOX"
			"XXXXXXXOOOOXOXOXXOOX"
			"XXXXXOOOOOOXOXOOOOOX"
			"XXXOOOOOOXOXOXOOOOOX"
			"XXXOOOOXOXOXOXXXXOOX"
			"OOOOXOOOOOOOOOOOXOOX"
			"OOOOXOOOOOOOOOOOXOOX"
			"XXOOXXXXOXXOXXXOXOOX"
			"XOOOOOOOOOOOOOOOOOOX"
			"XOPOOOOOOOOOOOOOOOOX"
			"XXXXXXXXXXXXXXXXXXXX",
		};

	};
};